FROM python:3.10-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


WORKDIR /app



COPY requirement.txt .
RUN pip install --upgrade pip \
    && pip wheel --no-deps --wheel-dir /wheels -r requirement.txt


COPY . /app










FROM python:3.10-slim

RUN addgroup --system app && adduser --system --ingroup app app

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-client \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app



COPY --from=builder /wheels /wheels
RUN pip install --no-cache-dir /wheels/* \
    && rm -rf /wheels


COPY --from=builder /app /app

RUN chown -R app:app /app

EXPOSE 8000

CMD

